### ISSUE TITLE
"Name server", "nameserver" and "server"

### ISSUE THREAD

**Issue by rdroms** [DNSOP/draft-ietf-dnsop-terminology-bis#13]
This issue concerns consistency and definition of some terms in the document.

"Name server", "name server" and, perhaps, "server" seem to be used interchangeably.  None of those terms have a formal definition in the document.  The terms are also used in conjunction with various modifiers like "authoritative server", "DNS server", etc.

While all those terms are likely pretty well-known, for the purposes of this document, un my opinion, it would be helpful to give a generic definition of "server", and how it is then combined with modifiers to form terminology for specific types of servers.

Based on the definition of "server", it would be helpful to include a definition for "name server", "name server" or "DNS server" (pick one) and then use that term uniformly throughout the document.

**Comment by paulehoffman** [comment]
Added a note about this in https://github.com/DNSOP/draft-ietf-dnsop-terminology-bis/pull/31

**Comment by paulehoffman** [comment]
Fixed in #31
