### ISSUE TITLE
Adopt terminology from RSSAC026, or at least point to it

### ISSUE THREAD

**Issue by paulehoffman** [DNSOP/draft-ietf-dnsop-terminology-bis#17]
See https://www.icann.org/en/system/files/files/rssac-026-14mar17-en.pdf

We could pull in those terms directly so that they all appear in the document, or we could at least point to the document (but then people won't know all the terms in it).

**Comment by moonshiner** [comment]
It does not appear that are any conflicts between the terms defined in rssac-26 and RFC7719.  

I vote for pulling in the terms directly DNSOP finds relevant (maybe all), *and* pointing to the document as the source.

**Comment by gmmoura** [comment]
I am missing *servers* in the terminology of [Fig 2 in this paper][imc2016]. 

For example, consider K-ROOT:
   * K-ROOT is a root server *letter*
   * It has  [50 *anycast sites*][root-severs], which are  distinct geographical locations
   * Each anycast site (e.g.: K-FRA, Frankfurt)  may have multiple *servers* behind its load balancer (K-FRA-S1, K-FRA-S2, K-FRA-S3, see [Fig. 12 in the same paper][imc2016].

So I think what is missing is this terminology is how to refer to  *individual servers* behind  a load balancer on a anycast site

[imc2016]:http://www.isi.edu/~johnh/PAPERS/Moura16b.pdf 
[root-severs]:http://root-servers.org/

**Comment by paulehoffman** [comment]
If the root ops didn't think of a need to be able to discuss such a server, do we really need that for the terminology document?

**Comment by gmmoura** [comment]
It depends on what is the goal of the document. If what we want is want a definitive document, then IMHO we should address it.  For the sake of completeness.

These individual servers are particularly important when referring to a DDoS attack: these middle boxes (load balancers) may behave in very different ways, and the load may be shared in distinct ways across these individual servers (see fig 12).

Otherwise, next time someone will write a paper about a DDoS on DNS, how s/he should refer to those individual servers?

**Comment by b4ldr** [comment]
i would vote to point to it.  similar to how rfc7720 points to rssac001

**Comment by danyork** [comment]
I agree that RSAAC026 should be referenced. I believe that "instance", "publish" and "server" would be useful additions. I don't know that the specific root zone terms need to be incorporated. 

I guess a general question would be (and I don't know the answer): do we anticipate creating RFCs that define operations and protocols used within the root zone?  If "yes" or "maybe", we should incorporate the terms.  If "probably not" or "no", then there could just be a new section about "Root Zone terminology" that specifically directs people to view RSAAC026 (and successor documents).

**Comment by paulehoffman** [comment]
Closed by #c10396c
