### ISSUE TITLE
Alphabetize terms? Or split up longer sections?

### ISSUE THREAD

**Issue by danyork** [DNSOP/draft-ietf-dnsop-terminology-bis#19]
Should terms in some sections be alphabetized? Or should some sections be split up more? I realize the current sorting is to start with the most relevant terms and then define ones that are connected to those terms, and on from there.

However, as I was reading through some of the longer sections (5 and 6), I found the current order a bit confusing.  For instance, at the beginning of section 5, it starts off with:

- Resolver
- Stub resolver
- Iterative mode
- Recursive mode
...

and I was saying "hey, what about a recursive resolver?"  and then I found that farther down the page.

But then after that it goes:

- Recursive resolver
- Priming
- Root hints
- Negative caching
- Authoritative servers
...

And then later:

- Zone transfer
- Secondary server
- Slave server
- Primary server
- Primary master

Which I just found confusing. (For instance, why does Primary appear after Secondary?)

I realize that alphabetizing is probably not the right solutions (unless we are making a "dictionary"), but I wonder about at least splitting up section 5 into separate sections for "DNS Servers" and "DNS Clients".  As it is right now I found it a bit confusing to move through all the terminology.

Just a suggestion - feel free to ignore, of course.

**Comment by paulehoffman** [comment]
Alphabetizing is indeed the wrong solution. We want a kind of a flow, but that could mean different things to different people. If you can suggest specific reorderings, that would be useful.

**Comment by crankycanuck** [comment]
Would the right answer be an alphabetic index?

**Comment by paulehoffman** [comment]
Alphabetic indexes in current RFCs have been a massive failure. They might be better when we have HTML RFCs, but we hope to be done with this before they exist.

**Comment by crankycanuck** [comment]
On Wed, Sep 20, 2017 at 08:17:15PM +0000, Paul Hoffman wrote:
> Alphabetic indexes in current RFCs have been a massive failure. They might be better when we have HTML RFCs, but we hope to be done with this before they exist.
> 

Well, arguably they alerady exist on the tools site.  So there's that.

Also, while alphabetic indexes have often failed, the class of RFCs
that contain only definitions, such as this one is, is pretty small.
I note that RFC 6365 has an index.  It's a little unfortunate that it
refers to page numbers instead of sections, but it's still helpful to
find a term.

A

-- 
Andrew Sullivan
ajs@anvilwalrusden.com

**Comment by paulehoffman** [comment]
Added an index in https://github.com/DNSOP/draft-ietf-dnsop-terminology-bis/pull/29
