### ISSUE TITLE
Definition for "root zone"

### ISSUE THREAD

**Issue by paulehoffman** [DNSOP/draft-ietf-dnsop-terminology-bis#20]
The current definition is:

The zone whose apex is the zero-length label.  Also sometimes called "the DNS root".

This definition is clearly DNS-centric because of the "zero-length"; other domain name systems might have the root zone have a name. The second sentence also makes it DNS-centric.

Proposal 1 (not DNS-centric): The zone at the apex of a domain name tree.

Proposal 2 (DNS-centric): The zone of in  DNS-based tree whose apex is the zero-length label. Also sometimes called "the DNS root".

**Comment by pspacek** [comment]
+1 for proposal 2. Personally I do not see value in describing non-DNS root in DNS-centric document.

**Comment by rdroms** [comment]
I prefer Proposal 2 (with minor editorial changes).  "Zone" is a DNS-centric term and the "root zone", in my opinion, refers to a part of the DNS namespace.  Other domain names that are outside of the DNS namespace are not included in the root zone.  Edited:

The zone of the DNS namespace whose apex is the zero-length label. Also sometimes called "the DNS root".

**Comment by paulehoffman** [comment]
We'll go with #2.
