### ISSUE TITLE
Insecure delegation

### ISSUE THREAD

**Issue by wkumari** [DNSOP/draft-ietf-dnsop-terminology-bis#26]
I have been unable to find a definition of "insecure delegation", but it is a term in common use.
The closest I found was some handwaving in the NSEC3 doc.

Perhaps worth adding?
[ Feel free to close issue if inappropriate, etc. ]

**Comment by paulehoffman** [comment]
We should define it. It appears starting in RFC 4956. The definition there is:
```
      insecure delegation:  refers to a signed name containing a delegation
         (NS RRset), but lacking a DS RRset, signifying a delegation to an
         unsigned subzone.
```
That seems fine to me

**Comment by paulehoffman** [comment]
Fixed in https://github.com/DNSOP/draft-ietf-dnsop-terminology-bis/pull/30
