### ISSUE TITLE
Split out error names in their own terms

### ISSUE THREAD

**Issue by paulehoffman** [DNSOP/draft-ietf-dnsop-terminology-bis#34]
During the discussion that led to RFC 7719, there was a request to split out error names in their own terms to make them easier to find in the document. Now with the index in place, this seems like a good idea.

**Comment by wkumari** [comment]
Oooh, yes, I think that this would be great.
[Sorry for the non-substantive / bikeshed comment]

**Comment by paulehoffman** [comment]
Entered in the doc as https://github.com/DNSOP/draft-ietf-dnsop-terminology-bis/pull/38
