### ISSUE TITLE
Private DNS / Split DNS

### ISSUE THREAD

**Issue by he32** [DNSOP/draft-ietf-dnsop-terminology-bis#39]
The definition of "Private DNS" in section 2 refers to "Split DNS"
in section 7.  However, "Split DNS" is defined at the end of section 5.

Now, I'm no big fan of "Split DNS", at least certain variants of it
where only a specific name tree (i.e. not from the root downwards, but
further down the tree) has an "internal" and a different "external"
view -- these become complicated to handle if/when you mix
DNSSEC into the picture.  Is that worthy of a few words of warning?
DNSSEC would tend to indicate that one of them is "truth" and the
other one is a "lie"...

**Comment by paulehoffman** [comment]
Fixed the reference issue in an earlier pull request.
