### ISSUE TITLE
Add terms from RFC 3833, RFC 5358, and RFC 7873

### ISSUE THREAD

**Issue by paulehoffman** [DNSOP/draft-ietf-dnsop-terminology-bis#4]
Suggested by Kazunori: I would like to add DNS threats and attack terms from RFC 3833 Threat
analysis, RFF 5358 Reflector attack and RFC 7873 Cookies.

**Comment by paulehoffman** [comment]
We would need more specific list of terms from RFC 3833 and RFC 5358 to see if they are applicable. The terms defined in RFC 7873 ("Off-path attacker", "Soft state", "Silently discarded", and "IP address") don't seem all that important to the DNS in general, even though the are useful in that document.

**Comment by paulehoffman** [comment]
@kfujiwara: can you give a specific list of terms you want from here? Or maybe we just add references to these documents saying that "more terms are defined there"?

**Comment by kfujiwara** [comment]
My idea was to add classification of attacks. for example, "cache poisoning", "name chaining" (too old),  (random subdomain attack), "reflector attacks" (RFC 5358) / "DNS amplification attacks" (RFC 7873), "Answer Forgery Attacks" (RFC 7873), (* DoS), (Packet interception / monkey-in-the-middle) (RFC 3833)

**Comment by paulehoffman** [comment]
If you can make a specific list with the definitions, that would be great. Even if it is just a few for now, we can add more later.

**Comment by paulehoffman** [comment]
This is over a year old, so I will close it. If you end up having some specific additions, it can be opened again.
