### ISSUE TITLE
Editorial nit in FQDN

### ISSUE THREAD

**Issue by paulehoffman** [DNSOP/draft-ietf-dnsop-terminology-bis#42]
The current definition says:
```
      The need for the term "fully qualified domain name" comes from the
      existence of partially qualified domain names, which are names
      where one or more of the earliest labels in the ordered list are
      omitted (for example, "www").  Such relative names are understood
      only by context.
```
The example is ambiguous. It should instead say:
```
      The need for the term "fully qualified domain name" comes from the
      existence of partially qualified domain names, which are names
      where one or more of the earliest labels in the ordered list are
      omitted (for example, a name of "www" derived from "www.example.net").
      Such relative names are understood
      only by context.
```

**Comment by paulehoffman** [comment]
PR is at https://github.com/DNSOP/draft-ietf-dnsop-terminology-bis/pull/43

**Comment by wessels** [comment]
FWIW I still find it confusing.  proposed alternative:

      The need for the term "fully qualified domain name" comes from the
      existence of partially qualified domain names, which are names
      where one or more of the later labels in the desired name are
      omitted.  For example, a user may enter "www" and rely on the application or
      operating system to append an appropriate domain suffix, turning it into "www.example.net".
      Such partially qualified names are understood only by context.

**Comment by suzworldwide** [comment]
Hi,

I’m a bit confused by “earliest” and “latest” here— Paul’s wording ("earliest labels in the ordered list”) made sense to me but Duane changed it (to “later labels in the desired list”). 

I’d suggest making it explicitly refer to "earlier labels in the ordering of nodes from the root of the tree,” because otherwise “earlier” or “later” both make my head hurt.


Suzanne

**Comment by wessels** [comment]
My thinking was that as I read the name (e.g. left-to-right) the "www" part is earliest and the "example.net" part is later.

The way we talk about ordering of labels seems sort of fundamental and it would be a shame to have it buried in this one definition of FQDN.  Its not really a terminology issue, but is there some way to make it more prominent and apply to the document as a whole?

**Comment by suzworldwide** [comment]
> On Nov 29, 2017, at 3:00 PM, Duane Wessels <notifications@github.com> wrote:
> 
> My thinking was that as I read the name (e.g. left-to-right) the "www" part is earliest and the "example.net" part is later.
> 
> 
Understood, was just thinking that it’s not obvious whether we mean reading order or evaluation order or something else unless we say so.
> The way we talk about ordering of labels seems sort of fundamental and it would be a shame to have it buried in this one definition of FQDN. Its not really a terminology issue, but is there some way to make it more prominent and apply to the document as a whole?
> 
Hadn't thought of it, but yes.

This is where I’m reminded there’s not really a definition of “domain name” out there to incorporate. There’s been a proposed definition kicking around for awhile, which was briefly discussed somewhere (the arcing list?) and I tried to get Ed Lewis to add to draft-lewis-domain-name.

I don’t think this document is the place to propose one not previously found in an RFC, although I’d be fine with the WG considering the question if the editors disagree.



Suzanne

**Comment by paulehoffman** [comment]
There is in fact a definition of "domain name" to incorporate. Under "Global DNS", it says:
```
      Composition of names -- A name in the global DNS has one or more
      labels.  The length of each label is between 0 and 63 octets
      inclusive.  In a fully-qualified domain name, the first label in
      the ordered list is 0 octets long; it is the only label whose
      length may be 0 octets, and it is called the "root" or "root
      label".  A domain name in the global DNS has a maximum total
      length of 255 octets in the wire format; the root represents one
      octet for this calculation.
```
We use "first" there, and we use it in a way that is the opposite of "earliest" in the current wording for FQDN, and thus the need for change. Duane's proposal is better than what we have now, but we can maybe even do better. How about:
```
  The need for the term "fully qualified domain name" comes from the
  existence of partially qualified domain names, which are names
  where one or more of the contiguous labels starting with the TLD
  in the desired name are omitted. For example, a user may enter "www"
  and rely on the application or operating system to append an
  appropriate domain suffix, such as turning it into "www.example.net".
  Such partially qualified names are understood only by context.
```
