### ISSUE TITLE
xml2rfc validation?

### ISSUE THREAD

**Issue by vcunat** [DNSOP/draft-ietf-dnsop-terminology-bis#66]
The nice xml2rfc tool barfs on me with the current and 09 drafts, both locally and [on the web](https://xml2rfc.tools.ietf.org/).  Are my expectations wrong?  Or am I doing something else wrong?

**Comment by vcunat** [comment]
Ah, I'm sorry, I've been an idiot.

_Even though double-checking, I was attempting to work with the xml embedded in html, by mistake._

**Comment by paulehoffman** [comment]
Whew! I was grinding through this trying to figure out what went wrong. (And, yes, I've done the same thing myself!)

**Comment by vcunat** [comment]
Typesetting nitpick: `xml2rfc --html` puts the `<artwork>` table of delegation types on the beginning of the section instead of putting it "inline" where the text expects it.  The other two `<artwork>` elements are directly under `<section>` and there it seems to work as expected, at least now (I see no guarantees).  Well, maybe the `xml2rfc` tool should try harder to put `<artwork>` inline.

Reading the [XML RFC](https://tools.ietf.org/html/rfc2629#section-2.3.1.3), I can't see a sure way around the problem, except for something like the LaTeX style &ndash; structure the text in a way that doesn't require the figure being on that very place, and that would feel unnecessarily cumbersome.  Anyway, `--text` is rendered as expected and the [live html](https://tools.ietf.org/html/draft-ietf-dnsop-terminology-bis-10#page-24) as well, so it's probably just OK.  I might be an exception that feels `--html` is significantly more comfortable to read than either.

**Comment by paulehoffman** [comment]
We'll try to remember this when we see the AUTH48 version. I suspect that the RFC Editor will try to keep the table with the text.
